rm(list = ls())
library(httr)
library(here)
library(jsonlite)
library(tidyverse)
library(lubridate)
library(janitor)
library(tidyquant)
library(hrbrthemes)
library(viridis)
library(paletteer)
library(covdata)
library(gghighlight)
library(ggtext)
library(directlabels)
library(tibbletime)
library(plotly)
Sys.setenv("plotly_username"="Calvinschoice")
Sys.setenv("plotly_api_key"="nlzCIoVJl6H4uWAeCiL9")

theme_set(theme_minimal())

rolling_sum <- rollify(sum, window = 14)
rolling_mean <- rollify(mean, window = 7)
