---
title: "COVID-19 Positive Rates in Missouri, Kansas, and Selected States"
author: "Jim Felps"
date: "6/14/2020"
output:
  powerpoint_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


```{r}
source('./scripts/Daily State Data.R')
source('./scripts/KC Metro Counties - Covdata.R')
source('./scripts/MO Counties - Covdata.R')
source('./scripts/Apple Mobility Data.R')
source('./scripts/Google Mobility Data.R')

```

## Missouri

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "MO",
         date > "2020-03-27") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity", col = "darkred", size = 1) +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "Red portion = this week's data",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )   +
  gghighlight(
    date >= floor_date(Sys.Date(), "weeks"),
    unhighlighted_colour = alpha("steelblue", 0.4)
  )

ggsave("images/missouri.png")
```

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "MO",
         date >= "2020-06-01") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity", , col = "darkred", size = 1) +
    labs(
      x = "",
      y = "",
      title = "Missouri Positivity Rate since June 1, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )  +
  gghighlight(
    date >= floor_date(Sys.Date(), "weeks"),
    unhighlighted_colour = alpha("steelblue", 0.4)
  )

ggsave("images/missouri_june.png")
```


## Kansas

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "KS",
         date > "2020-03-19") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity", col = "darkred", size = 1)  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "Red portion = this week's data",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        ) +
  gghighlight(
    date >= floor_date(Sys.Date(), "weeks"),
    unhighlighted_colour = alpha("steelblue", 0.4)
  )

ggsave("images/ks.png")
```

# County-level analysis - KC Metro

## New Positive Cases by County
```{r fig.height=8, fig.width=12}
metro_kc %>% 
  ggplot(aes(date, new_pos_7dma, group = county, color = county)) +
  geom_line(size = 1) +
  scale_color_viridis(discrete = TRUE) +
  labs(
    x = "",
    y = "",
    title = "Daily Positive Tests, 7 day moving average",
    caption = "Data from NYT Covid repository \nhttps://github.com/nytimes/covid-19-data"
  )

ggsave("images/metro_counties.png")
```

## All MO Counties

```{r fig.height=8, fig.width=12}
mo_counties_7ma %>% 
  ggplot(aes(date, new_pos_7dma, group = county)) +
  geom_line(size = 1, col = "darkred") +
  labs(
    x = "",
    y = "",
    title = "Daily Positive Tests, 7 day moving average",
    caption = "Data from NYT Covid repository \nhttps://github.com/nytimes/covid-19-data"
      ) +
  gghighlight(county %in% select_counties,
              unhighlighted_colour = alpha("steelblue", 0.4),
              label_key = county,
              label_params = list(size = 3))

ggsave("images/mo_counties.png")
```

## Apple Mobility Data - Metro Counties

```{r fig.height=8, fig.width=12}
vec_brks <- c(-50, 0, 50)
vec_labs <- vec_brks + 100

metro_driving %>% 
  ggplot(aes(date, index, group = region, color = over_under)) +
  geom_hline(yintercept = 0, color = "gray") +
  geom_col() +
  scale_y_continuous(breaks = vec_brks, labels = vec_labs) +
  scale_color_manual(values = c("firebrick", "steelblue")) +
  facet_wrap(~ region, nrow = 3, ncol = 3) +
  labs(x = "Date", 
       y = "Relative Mobility",
       title = "Relative Trends in Apple Maps Usage for Driving, KC Metro Area",
       caption = "Source: Apple\nVisual: Jim Felps") +
  guides(color = FALSE) +
  theme_minimal()

ggsave("images/metro_driving_apple.png")
```

# Google Mobility Data
```{r fig.height=8, fig.width=12}
metro_summary %>% 
  ggplot(aes(date, pct_change, group = type, color = type)) +
  geom_line(size = 0.5, color = "gray80") +
  geom_smooth(aes(color = type, group = type), se = FALSE) +
  theme_minimal() +
  facet_wrap(~ type, ncol = 3) +
  labs(x = "Date",
       y = "% Change from Baseline",
       title = "Relative Trends in Mobility for Kinds of Location in the KC Metro",
       subtitle = "Data relative to median activity from 1/3 to 2/6",
       caption = paste0("Source: Google LLC 'Google COVID-19 Community Mobility Reports'\nhttps://www.google.com/covid19/mobility/ Accessed: ", Sys.Date(),"\nVisual: Jim Felps")) +
  theme(legend.position = "none")

ggsave("images/metro_google.png")
```


# Select States with Problematic Trends \n(based on media coverage)

## Arizona

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "AZ",
         date > "2020-03-26") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/az.png")
```

## OK

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "OK",
         date > "2020-04-10") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/ok.png")
```

## Alabama

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "AL",
         date > "2020-03-21") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/al.png")
```

## Florida

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "FL",
         date > "2020-03-21") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/fl.png")
```

## Arkansas

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "AR",
         date > "2020-04-01") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/ar.png")
```

## California

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "CA",
         date > "2020-04-15") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/ca.png")
```

## Deleware

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "DE",
         date > "2020-04-01") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/de.png")
```

## Georgia

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "GA",
         date > "2020-03-01") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/ga.png")
```

## Oregan

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "OR",
         date > "2020-03-20") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/or.png")
```

## North Carolina

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "NC",
         date > "2020-03-15") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/nc.png")
```

## Nevada

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "NV",
         date > "2020-03-20") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/nv.png")
```

## Texas

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "TX",
         date > "2020-03-20") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/tx.png")
```

## Tennessee

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "TN",
         date > "2020-03-20") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/tn.png")
```

## Vermont

```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "VT",
         date > "2020-04-15") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/ca.png")
```

## New York


```{r fig.height=8, fig.width=12}
state_data %>%
  filter(state == "NY",
         date > "2020-03-12") %>%
  ggplot(aes(date, pos_rate_7dma)) +
    geom_line(stat = "identity")  +
    labs(
      x = "",
      y = "",
      title = "COVID Testing Positivity, 7 Day Moving Average",
      subtitle = "",
      caption = "Data from COVID Tracking project\nhttps://covidtracking.com/"
        )

ggsave("images/ny.png")
```

